config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("surveillance.urls")),

    path('accounts/', include('allauth.urls')),
]

surveillance/urls.py
from django.urls import path
from . import views

app_name    = "surveillance"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>/', views.delete, name="delete"), #←削除処理の割り当て、<int:pk>は数値であるものをpkという変数に割当て、ビューに渡す。
]

surveillance/models.py
from django.db import models

class Information(models.Model):

    class Meta:
        db_table = "information"

    url = models.URLField(verbose_name='URL',max_length=200)
    email = models.EmailField(verbose_name='メールアドレス',max_length=254)
    user_id = models.IntegerField(verbose_name="ユーザーID")
    
    """
    def __str__(self):
        return "登録済みサイトURL" + self.url +"メールアドレス"+ self.email
    """

surveillance/forms.py
from django import forms

from .models import Information

class InformationForm(forms.ModelForm):

    class Meta:
        model   = Information
        fields  = ['url','email','user_id']

surveillance/views.py
from django.shortcuts import render,redirect

from django.views import View



#TIPS:LoginRequiredMixinはリクエストしたユーザーがログインしているかどうかをチェックすることができる。
#TIPS:もし、ログインしていない場合、ログインページへリダイレクトする。使い方はビュークラスの第一引数として指定する。
from django.contrib.auth.mixins import LoginRequiredMixin



from .models import Information
from .forms import InformationForm


#TIPS:これでSurveillanceViewはログインしていないユーザーは全てのメソッドでトップページへリダイレクトされる。
class SurveillanceView(LoginRequiredMixin,View):

    def get(self, request, *args, **kwargs):

        #print(request.user.id)

        informations    = Information.objects.filter(user_id=request.user.id)

        #informations    = Information.objects.all()



        context = { "informations":informations }    
        return render(request,"surveillance/index.html",context)

    def post(self, request, *args, **kwargs):

        copied              = request.POST.copy()
        copied["user_id"]   = request.user.id


        #forms.pyを使ったほうが、フィールドが増えてもビューの書き換えは発生しないし、バリデーション(入力値のチェック)までできる
        form    = InformationForm(copied)

        if form.is_valid():
            print("バリデーションOK")
            form.save()

        else:
            print("バリデーションNG")

        return redirect("surveillance:index")

index   = SurveillanceView.as_view()


#レコードを削除する専用のビュー
class SurveillanceDeleteView(LoginRequiredMixin,View):

    def post(self, request, pk, *args, **kwargs):

        #TODO:ここでリクエストを送ったユーザーと削除対象のuser_idが一致しているかチェックする

        #主キーが合致するものを検索、対象を削除する。
        #TIPS:urls.pyにて、入力値のチェックは行っているのであえてforms.pyにてクラスを定義してバリデーションをする必要はない。
        informations  = Information.objects.filter(id=pk)

        #レコードが存在する場合、削除する。
        if informations:
            informations.delete()
        else:
            print("指定されたデータがありません")
        
        return redirect("surveillance:index")

delete  = SurveillanceDeleteView.as_view()


templates/surveillance/index.html
{% load static %} 
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>サイト監視君</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/49fbd67ac4.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="header">サイト監視君  <i class="far fa-eye"></i></div>

    <a href="{% url 'account_logout' %}">ログアウトする</a>

    <p>こんにちは {{ request.user.username }} さん</p>

    <p>こんにちは {{ request.user.last_name }} {{ request.user.first_name }}さん</p>


    <main class="container">
        <form method="POST">
            {% csrf_token %}
            <p>監視したいサイトURLを入力</p>
            <input type="url" placeholder="sample.com" name="url">
            
            <p>通知先メールアドレス</p>
            <input type="email" placeholder="sample@gmail.com" name="email">
            <input type="submit" value="登録">
        </form>

        {% for information in informations %}
        <div class="border">
            {{ information.url|urlize }}
            {{ information.email }}
            {# {{ information.user_id }} #}

            <!--
                urls.pyで決めたappnameとnameからurlの逆引きをする。スペース区切りで引数を指定
            -->
            <form action="{% url 'surveillance:delete' information.id %}" method="POST" style="display:inline-block;">
                {% csrf_token %}
                <input type="submit" value="削除">
            </form>
        </div>
        {% endfor %}

    </main>

</body>
</html>